### ISSUE TITLE
Expand model to handle 'blockpave' and 'concrete' materials

### ISSUE THREAD

**Issue by fritzjoostenz** [fritzjoostenz/cassandra_default_road_model#2]
Currently, if surface class is anything except 'ac' and 'cs', errors are thrown because other materials such as 'blockpave' and 'concrete' are not handled in the model.

Suggest we expand the model to handle birthday replacements for 'blockpave' and 'concrete'

**Comment by Potholer15** [comment]
Damn. Unintended. Got it

________________________________
From: Fritz Jooste ***@***.***>
Sent: Friday, 8 November 2024 3:10 pm
To: fritzjoostenz/cassandra_default_road_model ***@***.***>
Cc: Potholer15 ***@***.***>; Assign ***@***.***>
Subject: [fritzjoostenz/cassandra_default_road_model] Expand model to handle 'blockpave' and 'concrete' materials (Issue #2)


Currently, if surface class is anything except 'ac' and 'cs', errors are thrown because other materials such as 'blockpave' and 'concrete' are not handled in the model.

Suggest we expand the model to handle birthday replacements for 'blockpave' and 'concrete'

**Comment by Potholer15** [comment]
Updated in my working model, will commit to github
